### PR TITLE
Correct grammatical issues within installation.phtml

### PR DESCRIPTION
**Pull request by immattdavison**
Corrected grammatical issues within installation.phtml.

## What does this PR do?

This PR correct grammatical and spelling errors within the installation documentation.

### CODE REVIEW

**Review by gewenyu99 — APPROVED** [review]

**Comment by immattdavison** [comment]
That's ok, does this mean PRs in the Hacktoberfest repo will also not count as a separate PR?

**Comment by gewenyu99** [comment]
@immattdavison I'm gonna discuss this with our team 👀 I think we just do this to prevent like 70 PRs that move commas and periods and spaces around (which is common). I'll discuss with them, maybe we can have "flexible" rules. We'll keep you in the loop :)

**Comment by immattdavison** [comment]
> @immattdavison I'm gonna discuss this with our team 👀 I think we just do this to prevent like 70 PRs that move commas and periods and spaces around (which is common). I'll discuss with them, maybe we can have "flexible" rules. We'll keep you in the loop :)

For sure this makes sense, I can see why that would be a problem. Although I do also think I have made some valuable PRs despite them simply being to fix grammatical errors. It would be nice if it was one PR per repo maybe?

**Comment by gewenyu99** [comment]
@immattdavison So I've had a conversation with the team. TL;DR, I think we're gonna keep it as 1 PR accepted across all repos.

I think we're really not leaning toward opening the door for a lot of grammar-related PRs. I do a lot of the doc work around here, and old docs inherited with grammar issues are big pieces of "tech debt" for me. Your suggestions are really helpful and they've helped me a lot.

We're only enforcing this rule to be fair in a procedural way to everyone else involved. We're mostly focused on getting help on issues labeled `hacktoberfest` to make it easier for us to moderate and review the event effectively.

Again, really appreciate your help, but at the moment, we're not going to accept one PR per repo.

Anyway, happy Hacktoberfest, and good day to you!

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
