### PR TITLE
Ensure API endpoints have required params first

### PR DESCRIPTION
**Pull request by stnguyen90**
## What does this PR do?

Our SDKs sort API params to make required params first (because most languages need to have required params before optional). This fixes a bug where we weren't properly sorting params in the body/payload.

Closes: https://github.com/appwrite/appwrite/issues/5676

## Test Plan

Manual:

image

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/5676

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Review by gewenyu99 — APPROVED** [review]
Looks good to me. @stnguyen90 How are params sorted within required/non-required groups? Does it match SDK generator, too?

**Comment by stnguyen90** [comment]
> Looks good to me. @stnguyen90 How are params sorted within required/non-required groups? Does it match SDK generator, too?

@gewenyu99, yes, they match.

**Comment by eldadfux** [comment]
This should already come in the correct order from Appwrite, where did we see this?

**Review by eldadfux — APPROVED** [review]

**Comment by stnguyen90** [comment]
> This should already come in the correct order from Appwrite, where did we see this?

@eldadfux probably 1.3 when we made the param optional.

**Pull request merged**
