### PR TITLE
Deploy to DO button

### PR DESCRIPTION
**Pull request by lohanidamodar**
It's simple at the moment
image

image

### CODE REVIEW

**Comment by PineappleIOnic** [comment]
This is just a suggestion but I think a custom "Deploy to Digitalocean" button which fits Digital Ocean's design rather than ours might be better here to showcase that this uses another service that is not controlled by Appwrite. I'm not sure about eldad's opinion on this though :slightly_smiling_face:

**Comment by eldadfux** [comment]
> This is just a suggestion but I think a custom "Deploy to Digitalocean" button which fits Digital Ocean's design rather than ours might be better here to showcase that this uses another service that is not controlled by Appwrite. Just a small idea 🙂
> 
> They also have a design ready to go:
> DigitalOcean Button

This could work well with 1 provider, multiple ones might start to look messy.

**Comment by PineappleIOnic** [comment]
> > This is just a suggestion but I think a custom "Deploy to Digitalocean" button which fits Digital Ocean's design rather than ours might be better here to showcase that this uses another service that is not controlled by Appwrite. Just a small idea slightly_smiling_face
> > They also have a design ready to go:
> > DigitalOcean Button
> 
> This could work well with 1 provider, multiple ones might start to look messy.

When we start to get quite a few "Deploy with..." buttons we could have a popup or a page showing all the various providers you can deploy with, so the messiness is kept to it's own section and fits within that section

**Comment by eldadfux** [comment]
Closing in favor of a work-in-progress PR that @brandonroberts is working on.

**Pull request closed without merging**
