### PR TITLE
fix: add missing instantiation of functions #hacktoberfest

### PR DESCRIPTION
**Pull request by alanhoskins**
## What does this PR do?

Adds the missing instantiation of the `functions` variable in the functions Web example. 

```js
const client = new Client()
    .setEndpoint('https://[HOSTNAME_OR_IP]/v1')
    .setProject('[PROJECT_ID]');

// this is missing in the current docs
const functions = new Functions(client);

let promise = functions.createExecution('[FUNCTION_ID]');
```

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by gewenyu99** [comment]
@alanhoskins Hi there! Thanks for pointing this out to us, good catch. I think the addition of this line `const functions = new Functions(client);` is great, but could you clean up the PR a little and undo the changes where tabs and spaces are removed? 

It just makes it more difficult to review to have a bunch of unrelated changes :)

Thanks!

**Comment by alanhoskins** [comment]
Thanks @gewenyu99. I think I got that cleaned up. Line 832 appears to just be because it was bumped down from 830.

**Review by gewenyu99 — APPROVED** [review]
This looks good to me :)

**Comment by christyjacob4** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+org%3Aopen-runtimes+label%3Ahacktoberfest+created%3A%3E2021-01-01+state%3Aopen&type=issues&s=updated&o=asc) and help make Appwrite better :)

**Pull request merged**
