### PR TITLE
Fixed broken bold tags in storage.phtml

### PR DESCRIPTION
**Pull request by gewenyu99**
## What does this PR do?

Found a styling error in the storage docs that should be fixed real quick :)
## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

### CODE REVIEW

**Review by stnguyen90 — CHANGES_REQUESTED** [review]
@gewenyu99, while you're here, want to fix \`File\` in Create File?

image

**Comment by gewenyu99** [comment]
@stnguyen90 I added a fix for the `\``

Here's a question for you. We don't have inline monospace, do you think we can introduce something quickly so we can start using it to replace all other instances where we use `\`` for code related stuff? What alternative formatting do you suggest?

**Review by stnguyen90 — APPROVED** [review]

**Comment by stnguyen90** [comment]
@gewenyu99, I thought we were using the tag component to format code. Otherwise, we probably need to talk to Elad and Sara on this. The current problem is:

https://github.com/appwrite/appwrite/blob/822fc88fec134ec7553ee66a6e63232de724e633/public/styles/typography.less#L1-L5

which overrides all font to be Poppins rather than a monospace font. For example, `<code>Query.orderAsc()</code>` results in:

image

**Comment by gewenyu99** [comment]
@stnguyen90 The tag is really hard to read, I've seen some complaints :/

**Pull request merged**
