### PR TITLE
android:exported

### PR DESCRIPTION
**Pull request by s3ppo**
needed for:
compileSdkVersion 31

### CODE REVIEW

**Comment by christyjacob4** [comment]
@s3ppo Does this not apply to the android manifest in `getting-started-for-android`. ?

**Comment by s3ppo** [comment]
> @s3ppo Does this not apply to the android manifest in `getting-started-for-android`. ?

To be honest i have no idea what u mean 🙈🙈

**Comment by christyjacob4** [comment]
@s3ppo  Sorry, I meant , Don't we need to do the same thing is here 
https://github.com/appwrite/docs/blob/main/app/views/docs/getting-started-for-android.phtml#L55

**Comment by s3ppo** [comment]
Ah okay, if you mean to update it there also i can do that 👍

**Comment by s3ppo** [comment]
@christyjacob4 done

**Review by christyjacob4 — APPROVED** [review]

**Pull request merged**
