### PR TITLE
Environment variable refactored in appwrite/appwrite#1045

### PR DESCRIPTION
**Pull request by kodumbeats**
This PR includes the documentation changes associated with appwrite/appwrite#1045. This documents a breaking change, so it should not be released until #1045 is deployed.

### CODE REVIEW

**Comment by eldadfux** [comment]
Maybe we should add a new variable and mark the old one as deprecated at list for a few weeks / months?

**Comment by kodumbeats** [comment]
How's this look? I moved the old one to the bottom of the list.
deprecateOldEnvsInDocs

**Comment by eldadfux** [comment]
I might add a red warning (class="text-warning" iirc) saying: `[space](deprecated)` just after `version<0.8.0`

**Comment by kodumbeats** [comment]
envisdeprecated

**Pull request merged**
