### PR TITLE
Fix syntax errors in getting started example at the end

### PR DESCRIPTION
**Pull request by gewenyu99**
This fixes errors for Android and Flutter.

For Android:
- Fixes the use of single quotes for strings

For Flutter
- Missing semicolon
- Use of triple equal sign `===`, which is no longer supported.

### CODE REVIEW

**Review by christyjacob4 — APPROVED** [review]

**Comment by christyjacob4** [comment]
@gewenyu99  I noticed there are more instances in the same file where we're using single quotes for strings in kotlin. Please fix those as well. 

Also take a look at the entire flutter file too

**Review by christyjacob4 — CHANGES_REQUESTED** [review]
@gewenyu99  I noticed there are more instances in the same file where we're using single quotes for strings in kotlin. Please fix those as well. 

Also take a look at the entire flutter file too

**Review by abnegate — CHANGES_REQUESTED** [review]
The Android/Kotlin examples should also use `==` (structural equality) instead of `===` (referential equality) for these cases

**Comment by gewenyu99** [comment]
Android: 
Screen Shot 2022-05-09 at 10 03 36 AM

Flutter
Screen Shot 2022-05-09 at 10 15 38 AM

**Review by TorstenDittmann — APPROVED** [review]

**Pull request merged**
