### PR TITLE
Update upgrade.phtml

### PR DESCRIPTION
**Pull request by sungwon**
add note to bring down containers before running the installation script

### CODE REVIEW

**Comment by eldadfux** [comment]
Following up again, why do we need to stop the docker containers before installation? Docker CLI should already take care of most of the work.

**Comment by sungwon** [comment]
The upgrade did not work for me without stopping the containers, but I don't remember the details. I will retest this later this week when upgraded to 0.8

**Comment by mlucas-NU** [comment]
I ran into this as well. I believe I know my cause, but I don't know if it's the same cause as @sungwon is facing. Here's a partial screenshot :
Screen Shot 2021-06-14 at 4 20 26 PM
Note: The screenshot begins after my answers to the question about the DNS A record hostname.

In my case, my directory structure doesn't exactly match the directory structure that the tutorial expects. I'm running the upgrade from the root directory of a repository that solely exists to configure my appwrite servers. As such, I placed my **.env** and **docker-compose.yml** files at the root, where I ran the installation commands. Appwrite upgrades expect these files to be in a subdirectory named **appwrite**. I believe this is enough to throw off docker-compose.

Effectively, docker-compose doesn't see a file named **appwrite/docker-compose.yml** so it doesn't stop any running containers. Next, the upgrade script runs normally. In my case, that means it created an appwrite directory with default values for most of .env and docker-compose.yml. Finally, it tried to start new containers using the **appwrite/docker-compose.yml** configuration, but it ran into a naming collision because old containers were still running with the specified names.

I hope this helps.

**Comment by sungwon** [comment]
@mlucas-NU Thanks for the info. I don't believe this was the case for me. 

In any case, I was not able to reproduce this issue when upgrading to 0.8 (I did run into another unrelated issue but was able to successfully upgrade). In other words, I was able to upgrade without having to bring down containers first.

**Comment by eldadfux** [comment]
> @mlucas-NU Thanks for the info. I don't believe this was the case for me.
> 
> In any case, I was not able to reproduce this issue when upgrading to 0.8 (I did run into another unrelated issue but was able to successfully upgrade). In other words, I was able to upgrade without having to bring down containers first.

I think we can close this PR for now, until we have other insights.

**Pull request closed without merging**
